project:
  type: website
  output-dir: docs

website:
  site-url: https://ilyaszarif.github.io
  repo-url: "https://github.com/ilyaszarif/ilyaszarif.github.io"
  open-graph: true
  google-analytics:
    tracking-id: "G-9NCY9ZV6Z8"
    anonymize-ip: true
  title: "Data for Life..!"
  navbar:
    title: false
    #logo: images/logo/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: My Academic Identity
      - href: publications.qmd
        text: Publications
   
    right:
      - text: "{{< iconify bi github title='GitHub' >}}"
        href: https://github.com/ilyaszarif/
      - text: "{{< iconify fa6-brands bluesky title='Bluesky' >}}"
        href: https://bsky.app/profile/himalayanlynx.bsky.social
        rel: me
      - text: "{{< fa brands x title='X'>}}"
        href: https://x.com/himalayan_lynx
      - text: "{{< fa brands linkedin title='LinkedIN' >}}"
        href: https://www.linkedin.com/in/muhammad-ilyas-b0b733251/
      - text: "{{< fa brands researchgate title='ResearchGate' >}}"
        href: https://www.researchgate.net/profile/Muhammad-Ilyas-6
      - text: "{{< fa brands orcid title='ORCiD' >}}"
        href: https://orcid.org/0000-0002-9418-5442
      - text: "{{< iconify bi envelope title='E-mail me' >}}"
        href: "mailto:ilyaszarif@gmail.com"
  page-footer: 
    background: light
    left:  ©️ 2025, Muhammad Ilyas
    right: Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
    
format:
  html:
    page-layout: full
    sidebar: false
    smooth-scroll: true
    theme: 
     - green_theme.scss
   # css: styles.css
    #mainfont: Nunito
    toc: true
    include-in-header: logo.html



