project:
  type: website
  output-dir: docs

website:
  site-url: https://ilyaszarif.github.io
  open-graph: true
  twitter-card: 
    creator: "@himalayan_lynx"
  google-analytics:
    tracking-id: "G-9NCY9ZV6Z8"
    anonymize-ip: true
  title: "Data for Life..!"
  navbar:
    title: false
    #logo: images/logo/logo.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: My Academic Identity
      - href: publications.qmd
        text: Publications

      - text: "{{< fa brands github >}}"
        href: https://github.com/ilyaszarif/ilyaszarif.github.io
      - text: "{{< fa brands twitter >}}"
        href: https://x.com/himalayan_lynx
      - text: "{{< fa brands linkedin >}}"
        href: https://www.linkedin.com/in/muhammad-ilyas-b0b733251/
      - text: "{{< fa brands researchgate >}}"
        href: https://www.researchgate.net/profile/Muhammad-Ilyas-6
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0002-9418-5442
      - icon: envelope
        href: mailto:ilyaszarif@gmail.com
  page-footer: 
    background: light
    left: ©️ 2025, Muhammad Ilyas
    right: Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
format:
  html:
    page-layout: full
    sidebar: false
    smooth-scroll: true
    theme: 
     - green_theme.scss
   # css: styles.css
    #mainfont: Nunito
    toc: true
    include-in-header: logo.html



